# Generated by Django 3.1.7 on 2021-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='question',
            field=models.IntegerField(null=True),
        ),
    ]
