# Generated by Django 3.1.7 on 2021-03-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_solution_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='liked_by',
        ),
    ]
