# Generated by Django 3.1.7 on 2021-03-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='top',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
