# Generated by Django 3.1.7 on 2021-03-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='next_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_next_comment', to='home.comment'),
        ),
    ]
